const val GITHUB_REPO = """
    {
        "id": 187687182,
        "node_id": "MDEwOlJlcG9zaXRvcnkxODc2ODcxODI=",
        "name": "robs-smrt-test",
        "full_name": "rob-h-m/robs-smrt-test",
        "private": false,
        "owner": {
            "login": "rob-h-m",
            "id": 50835426,
            "node_id": "MDQ6VXNlcjUwODM1NDI2",
            "avatar_url": "https://avatars1.githubusercontent.com/u/50835426?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rob-h-m",
            "html_url": "https://github.com/rob-h-m",
            "followers_url": "https://api.github.com/users/rob-h-m/followers",
            "following_url": "https://api.github.com/users/rob-h-m/following{/other_user}",
            "gists_url": "https://api.github.com/users/rob-h-m/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rob-h-m/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rob-h-m/subscriptions",
            "organizations_url": "https://api.github.com/users/rob-h-m/orgs",
            "repos_url": "https://api.github.com/users/rob-h-m/repos",
            "events_url": "https://api.github.com/users/rob-h-m/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rob-h-m/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/rob-h-m/robs-smrt-test",
        "description": "Learning to use All The Things",
        "fork": false,
        "url": "https://api.github.com/repos/rob-h-m/robs-smrt-test",
        "forks_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/forks",
        "keys_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/teams",
        "hooks_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/hooks",
        "issue_events_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/events",
        "assignees_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/tags",
        "blobs_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/languages",
        "stargazers_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/stargazers",
        "contributors_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/contributors",
        "subscribers_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/subscribers",
        "subscription_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/subscription",
        "commits_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/merges",
        "archive_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/downloads",
        "issues_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/labels{/name}",
        "releases_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/deployments",
        "created_at": "2019-05-20T17:43:29Z",
        "updated_at": "2019-05-23T20:19:13Z",
        "pushed_at": "2019-05-21T19:48:59Z",
        "git_url": "git://github.com/rob-h-m/robs-smrt-test.git",
        "ssh_url": "git@github.com:rob-h-m/robs-smrt-test.git",
        "clone_url": "https://github.com/rob-h-m/robs-smrt-test.git",
        "svn_url": "https://github.com/rob-h-m/robs-smrt-test",
        "homepage": "",
        "size": 3,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 35,
        "license": null,
        "forks": 0,
        "open_issues": 35,
        "watchers": 0,
        "default_branch": "master"
    }
"""

const val GITHUB_REPO_ISSUES = """
    [
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/92",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/92/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/92/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/92/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/92",
        "id": 460033149,
        "node_id": "MDU6SXNzdWU0NjAwMzMxNDk=",
        "number": 92,
        "title": "Test Issue",
        "user": {
            "login": "ManApart",
            "id": 4498895,
            "node_id": "MDQ6VXNlcjQ0OTg4OTU=",
            "avatar_url": "https://avatars2.githubusercontent.com/u/4498895?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ManApart",
            "html_url": "https://github.com/ManApart",
            "followers_url": "https://api.github.com/users/ManApart/followers",
            "following_url": "https://api.github.com/users/ManApart/following{/other_user}",
            "gists_url": "https://api.github.com/users/ManApart/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ManApart/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ManApart/subscriptions",
            "organizations_url": "https://api.github.com/users/ManApart/orgs",
            "repos_url": "https://api.github.com/users/ManApart/repos",
            "events_url": "https://api.github.com/users/ManApart/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ManApart/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T18:28:33Z",
        "updated_at": "2019-06-24T18:28:33Z",
        "closed_at": null,
        "author_association": "CONTRIBUTOR",
        "body": "test"
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/91",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/91/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/91/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/91/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/91",
        "id": 460017574,
        "node_id": "MDU6SXNzdWU0NjAwMTc1NzQ=",
        "number": 91,
        "title": "Ensure node dependencies remain https",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:49:46Z",
        "updated_at": "2019-06-24T17:49:46Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"AS Andy the SCOS System Administrator,\r\n I WANT to keep all components of the Operating System up to date,\r\n SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.\r\n\r\nAcceptance Criteria:\r\n * All node dependencies remain as https endpoints\r\n * Running npm install does NOT change them back to http.\r\n\r\nNote, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.\r\n\r\n06-24-19: Migrated from SMRT-1369\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/90",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/90/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/90/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/90/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/90",
        "id": 460016938,
        "node_id": "MDU6SXNzdWU0NjAwMTY5Mzg=",
        "number": 90,
        "title": "Update Node libraries as needed",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:48:14Z",
        "updated_at": "2019-06-24T17:48:14Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"AS Andy the SCOS System Administrator,\r\n I WANT to keep all components of the Operating System up to date,\r\n SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.\r\n\r\nAcceptance Criteria:\r\n * Update node libraries  to be of the latest minor version for all node repositories.\r\n * Add a new step to the CI process which checks  if dependencies are not at their latest versions. \r\n\r\n \r\nTechnical Notes:\r\n - It could be useful to run a npm audit/upgrade/update? \r\n - This will likely involve not pinning to patch versions (or even minor versions).\r\n\r\nNote, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.\r\n\r\n06-24-19: Migrated from SMRT-1368\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/89",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/89/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/89/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/89/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/89",
        "id": 460016060,
        "node_id": "MDU6SXNzdWU0NjAwMTYwNjA=",
        "number": 89,
        "title": "Define process to update Node as needed (and update it)",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:45:54Z",
        "updated_at": "2019-06-24T17:45:54Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"AS Andy the SCOS System Administrator,\r\n I WANT to keep all components of the Operating System up to date,\r\n SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.\r\n\r\nAcceptance Criteria:\r\n * Verify if there are any known security risks with our existing versions of NodeJS\r\n * If there are necessary security patches which should be applied, apply these to discovery-ui.\r\n * Document the process on how to determine how, where, and when to update a core framework version.\r\n * Validate this process with Warner.\r\n * Write cards to perform these updates on other applications as necessary. \r\n\r\nNote, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.\r\n\r\n06-24-19: Migrated from SMRT-1356\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/88",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/88/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/88/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/88/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/88",
        "id": 460015160,
        "node_id": "MDU6SXNzdWU0NjAwMTUxNjA=",
        "number": 88,
        "title": "Restricted datasets - Ingest large Inrix dataset",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:43:44Z",
        "updated_at": "2019-06-24T17:43:44Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"As a data consumer I would like to have the existing CKAN data available in the new discovery ui so that I can access the datasets I already know and love.\r\n\r\nAC: \r\n * 239bf65d-5bc7-4a49-ae00-070de3c8a369 ingested\r\n\r\nTech notes:\r\n * Reaper is currently timing out on download (10min)\r\n * Reaper is being updated and might be able to handle it with new process\r\n * 4.3GB\r\n\r\n \r\n\r\n06-24-19: Migrated from SMRT-1265\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/87",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/87/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/87/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/87/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/87",
        "id": 460010643,
        "node_id": "MDU6SXNzdWU0NjAwMTA2NDM=",
        "number": 87,
        "title": "Discovery UI/API - multiple formats of dataset available for download",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:32:01Z",
        "updated_at": "2019-06-24T17:32:01Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"As a data consumer, \r\nI want a better data discovery experience,\r\nSo that I can find data in the platform more easily.\r\n\r\nAcceptance criteria:\r\n\r\nTBD (see Big Jake's mockup)\r\n\r\nTechnical notes:\r\n\r\nTBD\r\n\r\n06-24-19: Migrated from SMRT-1404\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/85",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/85/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/85/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/85/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/85",
        "id": 460009408,
        "node_id": "MDU6SXNzdWU0NjAwMDk0MDg=",
        "number": 85,
        "title": "Discovery UI - filter by remote v non-remote (tentative)",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:28:55Z",
        "updated_at": "2019-06-24T17:28:55Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"As a data consumer, \r\nI want a better data discovery experience,\r\nSo that I can find data in the platform more easily.\r\n\r\nAcceptance criteria:\r\n- Per Jake's mock-up have link/check box/button to show only non-remote dataset\r\n- If not checked/clicked show both remote and non-remote\r\n\r\nTechnical notes:\r\n- Can likely treat it like a facet\r\n\r\n06-24-19: Migrated from SMRT-1403\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/84",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/84/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/84/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/84/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/84",
        "id": 460005616,
        "node_id": "MDU6SXNzdWU0NjAwMDU2MTY=",
        "number": 84,
        "title": "Discovery UI - show completeness score as part of dataset search results",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:19:05Z",
        "updated_at": "2019-06-24T17:19:39Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"As a data consumer, \nI want a better data discovery experience,\nSo that I can find data in the platform more easily.\n\nAcceptance criteria:\n\n - Add completeness score as part of each dataset result in the search results\n- Talk to Jake about styling and/or profiling\n\nTech notes:\n- Requires an API change to include completeness in search results view\n- Keep performance in mind regarding Model.get and Model.get_all\n\n06-24-19: Migrated from SMRT-1402\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/83",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/83/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/83/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/83/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/83",
        "id": 460001815,
        "node_id": "MDU6SXNzdWU0NjAwMDE4MTU=",
        "number": 83,
        "title": "Discovery UI - add big and visible \"Submit Data\" button to UI",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:09:10Z",
        "updated_at": "2019-06-24T17:09:47Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"TABLE THIS UNTIL WE CAN CHAT ABOUT HOW TO INTEGRATE COLUMBUS SPECIFIC CONTENT INTO FOSS UI\n\nAs a data consumer, \nI want a better data discovery experience,\nSo that I can find data in the platform more easily.\n\nAcceptance criteria:\n\nTBD (see Big Jake's mockup)\n\nTechnical notes:\n\nTBD\n\n06-24-19: Migrated from SMRT-1401\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/82",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/82/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/82/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/82/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/82",
        "id": 459998673,
        "node_id": "MDU6SXNzdWU0NTk5OTg2NzM=",
        "number": 82,
        "title": "Discovery UI - reduce real estate taken up by \"Login\" area",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-24T17:00:15Z",
        "updated_at": "2019-06-24T17:01:24Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": ""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/81",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/81/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/81/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/81/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/81",
        "id": 459940608,
        "node_id": "MDU6SXNzdWU0NTk5NDA2MDg=",
        "number": 81,
        "title": "Master Chart for OS Local Dev",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": {
            "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/milestones/1",
            "html_url": "https://github.com/smartcitiesdata/discovery_ui/milestone/1",
            "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/milestones/1/labels",
            "id": 4436893,
            "node_id": "MDk6TWlsZXN0b25lNDQzNjg5Mw==",
            "number": 1,
            "title": "Sprint 54",
            "description": null,
            "creator": {
                "login": "rob-h-m",
                "id": 50835426,
                "node_id": "MDQ6VXNlcjUwODM1NDI2",
                "avatar_url": "https://avatars1.githubusercontent.com/u/50835426?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rob-h-m",
                "html_url": "https://github.com/rob-h-m",
                "followers_url": "https://api.github.com/users/rob-h-m/followers",
                "following_url": "https://api.github.com/users/rob-h-m/following{/other_user}",
                "gists_url": "https://api.github.com/users/rob-h-m/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rob-h-m/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rob-h-m/subscriptions",
                "organizations_url": "https://api.github.com/users/rob-h-m/orgs",
                "repos_url": "https://api.github.com/users/rob-h-m/repos",
                "events_url": "https://api.github.com/users/rob-h-m/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rob-h-m/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 2,
            "closed_issues": 0,
            "state": "open",
            "created_at": "2019-06-24T16:37:32Z",
            "updated_at": "2019-06-24T16:37:33Z",
            "due_on": null,
            "closed_at": null
        },
        "comments": 0,
        "created_at": "2019-06-24T14:12:15Z",
        "updated_at": "2019-06-24T16:37:33Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"As a developer implementing the Smart Cities data platform, I want an easy way to run the entire system on my machine.\n\nAcceptance Criteria:\n* All apps can be deployed locally using a single chart\n* Points to development tags of apps in docker hub?\n* Scos system tests runs locally\n* Include all dependent services as dependent charts\n\nTechnical Notes:\n* Depends on open sourcing charts\n* Default values should already have targeted minikube in the individual charts\n* Dependent services (as of today) include: OpenLDAP, Redis, KDP components\n\n06-24-19: Migrated from SMRT-1373\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/80",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/80/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/80/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/80/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/80",
        "id": 459937402,
        "node_id": "MDU6SXNzdWU0NTk5Mzc0MDI=",
        "number": 80,
        "title": "Discovery UI - display organization logo in dataset search results",
        "user": {
            "login": "SSackey",
            "id": 52043455,
            "node_id": "MDQ6VXNlcjUyMDQzNDU1",
            "avatar_url": "https://avatars2.githubusercontent.com/u/52043455?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SSackey",
            "html_url": "https://github.com/SSackey",
            "followers_url": "https://api.github.com/users/SSackey/followers",
            "following_url": "https://api.github.com/users/SSackey/following{/other_user}",
            "gists_url": "https://api.github.com/users/SSackey/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SSackey/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SSackey/subscriptions",
            "organizations_url": "https://api.github.com/users/SSackey/orgs",
            "repos_url": "https://api.github.com/users/SSackey/repos",
            "events_url": "https://api.github.com/users/SSackey/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SSackey/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": {
            "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/milestones/1",
            "html_url": "https://github.com/smartcitiesdata/discovery_ui/milestone/1",
            "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/milestones/1/labels",
            "id": 4436893,
            "node_id": "MDk6TWlsZXN0b25lNDQzNjg5Mw==",
            "number": 1,
            "title": "Sprint 54",
            "description": null,
            "creator": {
                "login": "rob-h-m",
                "id": 50835426,
                "node_id": "MDQ6VXNlcjUwODM1NDI2",
                "avatar_url": "https://avatars1.githubusercontent.com/u/50835426?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rob-h-m",
                "html_url": "https://github.com/rob-h-m",
                "followers_url": "https://api.github.com/users/rob-h-m/followers",
                "following_url": "https://api.github.com/users/rob-h-m/following{/other_user}",
                "gists_url": "https://api.github.com/users/rob-h-m/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rob-h-m/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rob-h-m/subscriptions",
                "organizations_url": "https://api.github.com/users/rob-h-m/orgs",
                "repos_url": "https://api.github.com/users/rob-h-m/repos",
                "events_url": "https://api.github.com/users/rob-h-m/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rob-h-m/received_events",
                "type": "User",
                "site_admin": false
            },
            "open_issues": 2,
            "closed_issues": 0,
            "state": "open",
            "created_at": "2019-06-24T16:37:32Z",
            "updated_at": "2019-06-24T16:37:33Z",
            "due_on": null,
            "closed_at": null
        },
        "comments": 0,
        "created_at": "2019-06-24T14:13:44Z",
        "updated_at": "2019-06-24T16:37:32Z",
        "closed_at": null,
        "author_association": "NONE",
        "body": "\"As a data consumer, \nI want a better data discovery experience,\nSo that I can find data in the platform more easily.\n\nAcceptance criteria:\n- Organization logos show up on dataset search results, per Jake's mockup\n- Aspect ratio/stretching should not look \"\"bad\"\"\n- Should be a link to the dataset (pending entry)\n- Should be accessible\n\nTechnical notes:\n- Dataset search only returns org name and title right now\n- Aspect ratio is not consistent with the images\n\n06-24-19: Migrated from SMRT-1399\""
    },
    {
        "url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/62",
        "repository_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui",
        "labels_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/62/labels{/name}",
        "comments_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/62/comments",
        "events_url": "https://api.github.com/repos/smartcitiesdata/discovery_ui/issues/62/events",
        "html_url": "https://github.com/smartcitiesdata/discovery_ui/issues/62",
        "id": 439280819,
        "node_id": "MDU6SXNzdWU0MzkyODA4MTk=",
        "number": 62,
        "title": "Post migration issues/concerns/thoughts/enhancements",
        "user": {
            "login": "jdenen",
            "id": 4671695,
            "node_id": "MDQ6VXNlcjQ2NzE2OTU=",
            "avatar_url": "https://avatars3.githubusercontent.com/u/4671695?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jdenen",
            "html_url": "https://github.com/jdenen",
            "followers_url": "https://api.github.com/users/jdenen/followers",
            "following_url": "https://api.github.com/users/jdenen/following{/other_user}",
            "gists_url": "https://api.github.com/users/jdenen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jdenen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jdenen/subscriptions",
            "organizations_url": "https://api.github.com/users/jdenen/orgs",
            "repos_url": "https://api.github.com/users/jdenen/repos",
            "events_url": "https://api.github.com/users/jdenen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jdenen/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2019-05-01T19:00:42Z",
        "updated_at": "2019-05-06T15:04:57Z",
        "closed_at": null,
        "author_association": "MEMBER",
        "body": "- [ ] smartcolumbusos.com front page search doesn't translate to discovery.smartcolumbusos.com search\r\n- [ ] IE 11 text overflows\r\n- [ ] Allow ability to unselect filters after searching (if you search with filters selected and get zero results its confusing)\r\n- [ ] Properly sanitize or render html in titles/descriptions\r\n- [ ] websocket API documentation for streams\n- [ ] Make search have a relevance heuristic so that searching for a dataset by name returns it as the first result\r\n- [ ] Visual indication that a dataset is remote and what that means in regards to functionality\r\n- [ ] Breadcrumb navigation (Only way right now to navigate right now is browser back button)\r\n- [ ] Keyword & Organization facets sorted alphabetically\r\n- [ ] search/browse by filetype\r\n- [ ] search/browse by stream/batch/remote\r\n- [ ] Organization home / about pages\r\n- [ ] Keyword & Organization facet search on \"Show more\" panel\"\r\n- [x] Group datasets which were grouped together in CKAN so that data dictionaries are grouped with their data\r\n- [x] Add ability to query remote datasets\r\n- [x] Improve descriptions being duplicated across legacy dataset resources from the same \"Dataset\" so we can tell the difference between them\r\n- [x] Add some ability for this to work responsively\r\n- [x] Tags (keywords) aren't included in search\r\n"
    }
]
"""

const val GITHUB_ISSUE =
        """
{
    "url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues/5",
    "repository_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test",
    "labels_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues/5/labels{/name}",
    "comments_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues/5/comments",
    "events_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/issues/5/events",
    "html_url": "https://github.com/rob-h-m/robs-smrt-test/issues/5",
    "id": 446763165,
    "node_id": "MDU6SXNzdWU0NDY3NjMxNjU=",
    "number": 5,
    "title": "Document streaming-metrics",
    "user": {
        "login": "rob-h-m",
        "id": 50835426,
        "node_id": "MDQ6VXNlcjUwODM1NDI2",
        "avatar_url": "https://avatars1.githubusercontent.com/u/50835426?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rob-h-m",
        "html_url": "https://github.com/rob-h-m",
        "followers_url": "https://api.github.com/users/rob-h-m/followers",
        "following_url": "https://api.github.com/users/rob-h-m/following{/other_user}",
        "gists_url": "https://api.github.com/users/rob-h-m/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rob-h-m/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rob-h-m/subscriptions",
        "organizations_url": "https://api.github.com/users/rob-h-m/orgs",
        "repos_url": "https://api.github.com/users/rob-h-m/repos",
        "events_url": "https://api.github.com/users/rob-h-m/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rob-h-m/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": {
        "url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/milestones/4",
        "html_url": "https://github.com/rob-h-m/robs-smrt-test/milestone/4",
        "labels_url": "https://api.github.com/repos/rob-h-m/robs-smrt-test/milestones/4/labels",
        "id": 4336170,
        "node_id": "MDk6TWlsZXN0b25lNDMzNjE3MA==",
        "number": 4,
        "title": "Sprint 51",
        "description": "",
        "creator": {
            "login": "rob-h-m",
            "id": 50835426,
            "node_id": "MDQ6VXNlcjUwODM1NDI2",
            "avatar_url": "https://avatars1.githubusercontent.com/u/50835426?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rob-h-m",
            "html_url": "https://github.com/rob-h-m",
            "followers_url": "https://api.github.com/users/rob-h-m/followers",
            "following_url": "https://api.github.com/users/rob-h-m/following{/other_user}",
            "gists_url": "https://api.github.com/users/rob-h-m/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rob-h-m/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rob-h-m/subscriptions",
            "organizations_url": "https://api.github.com/users/rob-h-m/orgs",
            "repos_url": "https://api.github.com/users/rob-h-m/repos",
            "events_url": "https://api.github.com/users/rob-h-m/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rob-h-m/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 35,
        "closed_issues": 15,
        "state": "open",
        "created_at": "2019-05-21T19:19:24Z",
        "updated_at": "2019-05-22T13:14:44Z",
        "due_on": "2019-05-28T07:00:00Z",
        "closed_at": null
    },
    "comments": 0,
    "created_at": "2019-05-21T18:30:52Z",
    "updated_at": "2019-05-21T20:11:10Z",
    "closed_at": "2019-05-21T20:11:10Z",
    "author_association": "OWNER",
    "body": "As a Delivery Lead,\nI want to see if ZenHub offers everything the team needs,\nSo that I can determine if we could use it instead of JIRA.",
    "closed_by": {
        "login": "rob-h-m",
        "id": 50835426,
        "node_id": "MDQ6VXNlcjUwODM1NDI2",
        "avatar_url": "https://avatars1.githubusercontent.com/u/50835426?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rob-h-m",
        "html_url": "https://github.com/rob-h-m",
        "followers_url": "https://api.github.com/users/rob-h-m/followers",
        "following_url": "https://api.github.com/users/rob-h-m/following{/other_user}",
        "gists_url": "https://api.github.com/users/rob-h-m/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rob-h-m/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rob-h-m/subscriptions",
        "organizations_url": "https://api.github.com/users/rob-h-m/orgs",
        "repos_url": "https://api.github.com/users/rob-h-m/repos",
        "events_url": "https://api.github.com/users/rob-h-m/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rob-h-m/received_events",
        "type": "User",
        "site_admin": false
    }
}
"""

const val ZENHUB_EPIC_ISSUES = """
{
    "epic_issues": [
        {
            "issue_number": 4,
            "repo_id": 187687182,
            "issue_url": "https://github.com/rob-h-m/robs-smrt-test/issues/4"
        },
        {
            "issue_number": 15,
            "repo_id": 187687182,
            "issue_url": "https://github.com/rob-h-m/robs-smrt-test/issues/15"
        }
    ]
}
"""

const val ZENHUB_EPIC = """
{
    "issues": [
        {
            "repo_id": 187687182,
            "issue_number": 5,
            "estimate": {
                "value": 1
            },
            "is_epic": false,
            "pipelines": [
                {
                    "workspace_id": "5ce41a70b67fdd19a95b76c8",
                    "name": "New Issues",
                    "pipeline_id": "5ce41a70b67fdd19a95b76c2"
                }
            ],
            "pipeline": {
                "workspace_id": "5ce41a70b67fdd19a95b76c8",
                "name": "closed",
                "pipeline_id": "5ce41a70b67fdd19a95b76c2"
            }
        }
    ],
    "total_epic_estimates": {
        "value": 25
    },
    "pipeline": {
        "workspace_id": "5ce41a70b67fdd19a95b76c8",
        "name": "In Progress",
        "pipeline_id": "5ce41a70b67fdd19a95b76c5"
    },
    "pipelines": [
        {
            "workspace_id": "5ce41a70b67fdd19a95b76c8",
            "name": "In Progress",
            "pipeline_id": "5ce41a70b67fdd19a95b76c5"
        }
    ]
}
"""